// src/templates/react/js-part.ts
import type { TemplatePart } from "../../types.js";

/**
 * React (Vite) source files, JavaScript slice. Same app as the TS slice, no
 * type-checking scaffolding.
 */

const VITE_CONFIG_JS = [
  'import { defineConfig } from "vite";',
  'import react from "@vitejs/plugin-react";',
  "",
  "// https://vite.dev/config/",
  "export default defineConfig({",
  "  plugins: [react()],",
  "});",
  "",
].join("\n");

const INDEX_HTML = [
  "<!doctype html>",
  '<html lang="en">',
  "  <head>",
  '    <meta charset="UTF-8" />',
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  "    <title>frontend-starter · react</title>",
  "  </head>",
  "  <body>",
  '    <div id="root"></div>',
  '    <script type="module" src="/src/main.jsx"></script>',
  "  </body>",
  "</html>",
  "",
].join("\n");

const MAIN_JSX = [
  'import { StrictMode } from "react";',
  'import { createRoot } from "react-dom/client";',
  'import App from "./App.jsx";',
  'import "./styles.css";',
  "",
  'createRoot(document.getElementById("root")).render(',
  "  <StrictMode>",
  "    <App />",
  "  </StrictMode>,",
  ");",
  "",
].join("\n");

const APP_JSX = [
  "export default function App() {",
  "  return (",
  '    <main className="app">',
  "      <h1>React + Vite + JavaScript</h1>",
  "      <p>",
  "        Edit <code>src/App.jsx</code> and save to test HMR.",
  "      </p>",
  "    </main>",
  "  );",
  "}",
  "",
].join("\n");

export function reactJsPart(): TemplatePart {
  return {
    id: "react/_js",
    files: {
      "index.html": INDEX_HTML,
      "vite.config.js": VITE_CONFIG_JS,
      "src/main.jsx": MAIN_JSX,
      "src/App.jsx": APP_JSX,
    },
  };
}

// src/templates/solid/js-part.ts
import type { TemplatePart } from "../../types.js";

/**
 * SolidJS (Vite) source files, JavaScript slice. Mirrors the TypeScript
 * slice minus tsconfig and typed entry points. `viteConfig()` is exported so
 * the Tailwind overlay can re-emit the config with the plugin added from the
 * same source of truth.
 */

export function viteConfig(withTailwind: boolean): string {
  return [
    'import { defineConfig } from "vite";',
    ...(withTailwind ? ['import tailwindcss from "@tailwindcss/vite";'] : []),
    'import solid from "vite-plugin-solid";',
    "",
    "export default defineConfig({",
    withTailwind ? "  plugins: [tailwindcss(), solid()]," : "  plugins: [solid()],",
    "});",
    "",
  ].join("\n");
}

const INDEX_HTML = [
  "<!doctype html>",
  '<html lang="en">',
  "  <head>",
  '    <meta charset="UTF-8" />',
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  "    <title>frontend-starter · solid</title>",
  "  </head>",
  "  <body>",
  '    <div id="root"></div>',
  '    <script type="module" src="/src/index.jsx"></script>',
  "  </body>",
  "</html>",
  "",
].join("\n");

const INDEX_JSX = [
  'import { render } from "solid-js/web";',
  'import "./styles.css";',
  'import App from "./App";',
  "",
  'const root = document.getElementById("root");',
  "",
  "render(() => <App />, root);",
  "",
].join("\n");

const APP_JSX = [
  'import { createSignal } from "solid-js";',
  "",
  "function App() {",
  "  const [count, setCount] = createSignal(0);",
  "  return (",
  '    <main class="app">',
  "      <h1>Solid + Vite + JavaScript</h1>",
  "      <p>",
  "        Edit <code>src/App.jsx</code> and save to test HMR.",
  "      </p>",
  '      <button type="button" onClick={() => setCount(count() + 1)}>',
  "        count is {count()}",
  "      </button>",
  "    </main>",
  "  );",
  "}",
  "",
  "export default App;",
  "",
].join("\n");

export function solidJsPart(): TemplatePart {
  return {
    id: "solid/_js",
    files: {
      "index.html": INDEX_HTML,
      "vite.config.js": viteConfig(false),
      "src/index.jsx": INDEX_JSX,
      "src/App.jsx": APP_JSX,
    },
  };
}
