// src/templates/angular/ts-part.ts
import type { TemplatePart } from "../../types.js";

/**
 * Angular 20 source files (TypeScript-only framework). Ships stable zoneless
 * change detection (`provideZonelessChangeDetection()`), so there is no
 * polyfill or zone.js dependency to maintain. `angular.json` uses the modern
 * @angular/build application builder.
 */

const ANGULAR_JSON = {
  $schema: "./node_modules/@angular/cli/lib/config/schema.json",
  version: 1,
  newProjectRoot: "projects",
  projects: {
    app: {
      projectType: "application",
      root: "",
      sourceRoot: "src",
      prefix: "app",
      architect: {
        build: {
          builder: "@angular/build:application",
          options: {
            outputPath: "dist/app",
            index: "src/index.html",
            browser: "src/main.ts",
            polyfills: [],
            tsConfig: "tsconfig.json",
            assets: [],
            styles: ["src/styles.css"],
            scripts: [],
            prerender: false,
            ssr: false,
          },
          configurations: {
            production: {
              budgets: [
                { type: "initial", maximumWarning: "500kB", maximumError: "1MB" },
                { type: "anyComponentStyle", maximumWarning: "4kB", maximumError: "8kB" },
              ],
              outputHashing: "all",
            },
            development: {
              optimization: false,
              extractLicenses: false,
              sourceMap: true,
            },
          },
          defaultConfiguration: "production",
        },
        serve: {
          builder: "@angular/build:dev-server",
          configurations: {
            production: { buildTarget: "app:build:production" },
            development: { buildTarget: "app:build:development" },
          },
          defaultConfiguration: "development",
        },
      },
    },
  },
};

const TSCONFIG = JSON.stringify(
  {
    compileOnSave: false,
    compilerOptions: {
      strict: true,
      noImplicitOverride: true,
      noPropertyAccessFromIndexSignature: true,
      noImplicitReturns: true,
      noFallthroughCasesInSwitch: true,
      skipLibCheck: true,
      isolatedModules: true,
      esModuleInterop: true,
      experimentalDecorators: false,
      importHelpers: true,
      target: "ES2022",
      module: "preserve",
    },
    angularCompilerOptions: {
      enableI18nLegacyMessageIdFormat: false,
      strictInjectionParameters: true,
      strictTemplates: true,
      typeCheckHostBindings: true,
    },
    files: ["src/main.ts"],
    include: ["src/**/*.d.ts"],
  },
  null,
  2,
);

const INDEX_HTML = [
  "<!doctype html>",
  '<html lang="en">',
  "  <head>",
  '    <meta charset="UTF-8" />',
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  "    <title>frontend-starter · angular</title>",
  "  </head>",
  "  <body>",
  "    <app-root></app-root>",
  "  </body>",
  "</html>",
  "",
].join("\n");

const MAIN_TS = [
  'import { bootstrapApplication } from "@angular/platform-browser";',
  "",
  'import { appConfig } from "./app/app.config";',
  'import { App } from "./app/app";',
  "",
  "bootstrapApplication(App, appConfig).catch((err) => console.error(err));",
  "",
].join("\n");

const APP_CONFIG_TS = [
  "import {",
  "  ApplicationConfig,",
  "  provideBrowserGlobalErrorListeners,",
  "  provideZonelessChangeDetection,",
  '} from "@angular/core";',
  "",
  "export const appConfig: ApplicationConfig = {",
  "  providers: [provideBrowserGlobalErrorListeners(), provideZonelessChangeDetection()],",
  "};",
  "",
].join("\n");

const APP_TS = [
  'import { Component, signal } from "@angular/core";',
  "",
  "@Component({",
  '  selector: "app-root",',
  '  templateUrl: "./app.html",',
  "  styles: ``,",
  "})",
  "export class App {",
  "  protected readonly count = signal(0);",
  "}",
  "",
].join("\n");

const APP_HTML = [
  '<main class="app">',
  "  <h1>Angular + TypeScript</h1>",
  "  <p>",
  "    Edit <code>src/app/app.html</code> and save to test HMR.",
  "  </p>",
  '  <button type="button" (click)="count.set(count() + 1)">',
  "    count is {{ count() }}",
  "  </button>",
  "</main>",
  "",
].join("\n");

export function angularTsPart(): TemplatePart {
  return {
    id: "angular/_ts",
    files: {
      "angular.json": JSON.stringify(ANGULAR_JSON, null, 2) + "\n",
      "tsconfig.json": TSCONFIG,
      "src/index.html": INDEX_HTML,
      "src/main.ts": MAIN_TS,
      "src/app/app.config.ts": APP_CONFIG_TS,
      "src/app/app.ts": APP_TS,
      "src/app/app.html": APP_HTML,
    },
  };
}

// src/templates/solid/ts-part.ts
import type { TemplatePart } from "../../types.js";

/**
 * SolidJS (Vite) source files, TypeScript slice. `viteConfig()` is exported
 * so the Tailwind overlay can re-emit the config with the plugin added from
 * the same source of truth.
 */

export function viteConfig(withTailwind: boolean): string {
  return [
    'import { defineConfig } from "vite";',
    ...(withTailwind ? ['import tailwindcss from "@tailwindcss/vite";'] : []),
    'import solid from "vite-plugin-solid";',
    "",
    "export default defineConfig({",
    withTailwind ? "  plugins: [tailwindcss(), solid()]," : "  plugins: [solid()],",
    "});",
    "",
  ].join("\n");
}

const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      allowImportingTsExtensions: true,
      verbatimModuleSyntax: true,
      moduleDetection: "force",
      noEmit: true,
      jsx: "preserve",
      jsxImportSource: "solid-js",
      strict: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noFallthroughCasesInSwitch: true,
      skipLibCheck: true,
      types: ["vite/client"],
    },
    include: ["src", "vite.config.ts"],
  },
  null,
  2,
);

const INDEX_HTML = [
  "<!doctype html>",
  '<html lang="en">',
  "  <head>",
  '    <meta charset="UTF-8" />',
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  "    <title>frontend-starter · solid</title>",
  "  </head>",
  "  <body>",
  '    <div id="root"></div>',
  '    <script type="module" src="/src/index.tsx"></script>',
  "  </body>",
  "</html>",
  "",
].join("\n");

const INDEX_TSX = [
  'import { render } from "solid-js/web";',
  'import "./styles.css";',
  'import App from "./App";',
  "",
  'const root = document.getElementById("root");',
  "",
  "render(() => <App />, root!);",
  "",
].join("\n");

const APP_TSX = [
  'import type { Component } from "solid-js";',
  "",
  'import { createSignal } from "solid-js";',
  "",
  "const App: Component = () => {",
  "  const [count, setCount] = createSignal(0);",
  "  return (",
  '    <main class="app">',
  "      <h1>Solid + Vite + TypeScript</h1>",
  "      <p>",
  "        Edit <code>src/App.tsx</code> and save to test HMR.",
  "      </p>",
  '      <button type="button" onClick={() => setCount(count() + 1)}>',
  "        count is {count()}",
  "      </button>",
  "    </main>",
  "  );",
  "};",
  "",
  "export default App;",
  "",
].join("\n");

export function solidTsPart(): TemplatePart {
  return {
    id: "solid/_ts",
    files: {
      "index.html": INDEX_HTML,
      "vite.config.ts": viteConfig(false),
      "tsconfig.json": TSCONFIG,
      "src/index.tsx": INDEX_TSX,
      "src/App.tsx": APP_TSX,
    },
  };
}
